### ISSUE TITLE
Startmin not working?

### ISSUE THREAD

**Issue by Hexaae** [YELLO-belly/cdaudio-winmm#4]
I use: 

```
100
#
# cdaudioplr CD music volume override control.
# Change the number to the desired volume level (0-100).

[options]
# Enable debug log
Log = 0

# Start cdaudioplr minimized in the taskbar
StartMin = 1

# Set cdaudioplr to run on the last CPU core
LastCore = 0

```
but doesn't work... won't start minimized... mmh

**Comment by YELLO-belly** [comment]
Pulled 1.6.3 and re-posted a fixed version.

**Comment by Hexaae** [comment]
Does work now, but there's an ugly Prompt window opening and closing at launch... :-\

**Comment by YELLO-belly** [comment]
The cmd promt that shows momentarily when cdaudioplr.exe is auto started by the winmm wrapper is normal behaviour now. The previous  method of opening the player with the ShellExecuteA function was not working reliably.

**Comment by Hexaae** [comment]
Strange, never had a single fail with previous beta and _Earthworm Jim SE_, and _Pitfall The Mayan Adventure_...
Can you add a "OLDEXECUTE" option maybe, for those like me who hate to see that prompt pop-up?

**Comment by YELLO-belly** [comment]
I'm sorry you do not like it but it does work reliably now and the small cosmetic annoyance of sometimes seeing a cmd prompt is a fair trade off compared to the unreliable old implementation.

The automatic starting of cdaudioplr.exe is supposed to work in the following manner:

1. start cdaudioplr.exe.
2. Enter a waiting loop so that cdaudioplr has time to initialize.
3. Continue sending commands to cdaudioplr.exe after the wait loop.

With the old method of using ShellExecuteA this is what seemed to happen instead:

0. Try to start cdaudioplr.exe and lock up.
1. Enter a waiting loop before cdaudioplr.exe is fully started.
2. After the wait loop continue starting up cdaudioplr.exe.
3. Start sending commands to cdaudioplr.exe

As can be seen this should not work at all but depending on system latency it sometimes did work and on a slower system might even work all the time but this was definitely not working as intended.

The problem was with how the ShellExecuteA function works when tied to the winmm wrapper. So the only way I found to make it work was to use the system command instead and call the normal "start" command that one would also use in a batch file. The start command fires up the cmd prompt and proceeds to start cdaudioplr.exe.

**Comment by Hexaae** [comment]
Yes I hate that 😉
Thanks for detailed explanation... what about a possible workaround with VBS?
https://stackoverflow.com/questions/45549442/use-cmd-c-but-hide-the-console-window

**Comment by YELLO-belly** [comment]
Not feasible to run from inside a dll file in code but you can set AutoStart = 0 in winmm.ini and write your own starter using a vbs script.

**Comment by Hexaae** [comment]
Someone proposed:
`start /b cmd /c "command"`... but I guess will hide new win only when started from an already opened prompt...

**Comment by YELLO-belly** [comment]
Try this vbscript (copy it to notepad and save it in the game directory as for example **start_game.vbs**):

```
'This is a vbscript to launch cdaudiopler.exe followed by a wait and the game program launch.
Dim objShell
Set objShell = WScript.CreateObject( "WScript.Shell" )
objShell.Run(".\\mcicda\\cdaudioplr.exe")

'Sleep for 1000 milliseconds (1 second)
WScript.Sleep 1000

'Change the GAME.exe to match your game exectable name:
objShell.Run("GAME.exe")
wscript.quit
```
You can make a shortcut of this vbs file to the desktop and change its icon to that of the game executable. Also remember to change "**AutoStart = 0**" in the winmm.ini file.
